### ISSUE TITLE
Login required for building a Markdown codelab

### ISSUE THREAD

**Issue by cassierecher** [googlecodelabs/tools#337]

**Comment by hemchander23** [comment]
+1 We are trying to automate codelab generation via Jenkins. Could you pl. fix that

**Comment by kun432** [comment]
+1

**Comment by spandl** [comment]
I am using also a local Mac and get the same request

`Authorize me at following URL, please:`
`https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id= ...`

Then I am asked a `Code`.

What do I need to enter here?

**Comment by Enjolras67** [comment]
I met the same issue:
Authorize me at following URL, please:
https://accounts.google.com/o/oauth2/auth?access_type=offline&....
Is there any work around?

**Comment by spesnova** [comment]
You won't be asked the code if you pass the markdown file path to `claat` command like this:

```console
 $ claat export document.md
 ok      your-md-based-codelab
```

https://github.com/googlecodelabs/tools#ok-how-do-i-use-it

**Comment by fabstu** [comment]
I'm running `claat export doc.md` inside a Github Action and I get

```
Run claat export doc.md
err	doc.md unable to obtain access token for "goog"
Authorize me at following URL, please:
```

@spesnova do you have any idea why?

**Comment by SaiEmaniFlipp** [comment]
I am seeing the following error when trying to export a markdown file.
```
 claat export codelab.md 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x132a745]

goroutine 7 [running]:
github.com/googlecodelabs/tools/claat/fetch/drive/auth.(*Helper).DriveClient(...)
	/Users/saiemani/Go/src/github.com/googlecodelabs/tools/claat/fetch/drive/auth/auth.go:90
github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).slurpRemoteBytes(0xc00007c8c0, 0xc000029780, 0x2d, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/saiemani/Go/src/github.com/googlecodelabs/tools/claat/fetch/fetch.go:388 +0x55
github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).slurpBytes(0xc00007c8c0, 0x7ffeefbffa0d, 0xa, 0xc000026d06, 0xa, 0xc000024210, 0x2d, 0x0, 0x0, 0x0, ...)
	/Users/saiemani/Go/src/github.com/googlecodelabs/tools/claat/fetch/fetch.go:254 +0x430
github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).SlurpImages.func1(0xc00007c8c0, 0x7ffeefbffa0d, 0xa, 0xc000026d06, 0xa, 0xc0000309c0, 0xc0001fa070)
	/Users/saiemani/Go/src/github.com/googlecodelabs/tools/claat/fetch/fetch.go:205 +0x98
created by github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).SlurpImages
	/Users/saiemani/Go/src/github.com/googlecodelabs/tools/claat/fetch/fetch.go:203 +0x151
```

**Comment by ralphilius** [comment]
It will ask for authorize if I pass `-o out` options:

`claat export *.md -o out`

**Comment by fabstu** [comment]
I has this problem when the out-folder did not exist. After Increated the folder before executing the command the problem went away.

**Comment by ralphilius** [comment]
> I had this problem when the out-folder did not exist. After I created the folder before executing the command the problem went away.

I tried to create `out` folder but still got error

**Comment by stefanodoni** [comment]
I had the same error when converting a Google Doc to markdown.

If you click on the link, you will be redirected to a login page, which returns an URL that you need to paste into the terminal ("Code:"), then everything works.

A small UX issue.

**Comment by contributorpw** [comment]
@stefanodoni what if you don't have a google account or you can't provide a personal one?

**Comment by Urena-luis** [comment]
I am running  $ claat export document.md and I am presented with an authorization link, but the authorization never completes. The page just hangs
