### ISSUE TITLE
Unable to insert image when generating from markdown

### ISSUE THREAD

**Issue by rh-2019** [googlecodelabs/tools#560]
Hi, my issue is unable to insert images when use markdown to generate the codelab.

1. First, I tried the syntax in sample markdown, but I met NPE when calling claat export.
The syntax is
`![alt text](https://drive.google.com/uc?export=view&id=1JukC56Ru7Z5zhlkAuDOba-ZUWPW-NGh3)` 
The error is 
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7199b5]

goroutine 7 [running]:
github.com/googlecodelabs/tools/claat/fetch/drive/auth.(*Helper).DriveClient(...)
	/home/qusandbox7/go/pkg/mod/github.com/googlecodelabs/tools/claat@v0.0.0-20200918190358-3cc6629c4d3d/fetch/drive/auth/auth.go:90
github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).slurpRemoteBytes(0xc0002f65c0, 0xc000030420, 0x4c, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/qusandbox7/go/pkg/mod/github.com/googlecodelabs/tools/claat@v0.0.0-20200918190358-3cc6629c4d3d/fetch/fetch.go:396 +0x55
github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).slurpBytes(0xc0002f65c0, 0x7ffd551c909f, 0x7, 0xc00002f780, 0x1a, 0xc0000347d0, 0x4c, 0x0, 0x0, 0x9bca3a, ...)
	/home/qusandbox7/go/pkg/mod/github.com/googlecodelabs/tools/claat@v0.0.0-20200918190358-3cc6629c4d3d/fetch/fetch.go:258 +0x408
github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).SlurpImages.func1(0xc0002f65c0, 0x7ffd551c909f, 0x7, 0xc00002f780, 0x1a, 0xc00007d560, 0xc00033e000)
	/home/qusandbox7/go/pkg/mod/github.com/googlecodelabs/tools/claat@v0.0.0-20200918190358-3cc6629c4d3d/fetch/fetch.go:209 +0x98
created by github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).SlurpImages
	/home/qusandbox7/go/pkg/mod/github.com/googlecodelabs/tools/claat@v0.0.0-20200918190358-3cc6629c4d3d/fetch/fetch.go:207 +0x151`

2. Then I tried to insert HTML directly.
<img src='https://drive.google.com/uc?export=view&id=1JukC56Ru7Z5zhlkAuDOba-ZUWPW-NGh3' width=500px>
It looks like the whole block is ignored by the parser and no elements rendered on the HTML page.

In addition, the document about using markdown is a bit out of date, lots of syntaxes have been changed needing to be found in the issues one by one...

Thanks.

**Comment by Rada8732** [comment]
Check image comparability

**Comment by rh-2019** [comment]
> Check image comparability
Thanks for your reply. Could u explain more? If you are saying it's caused by image, I already tried different images, and not working...

**Comment by Rada8732** [comment]
What toolkit are you using

**Comment by rh-2019** [comment]
> What toolkit are you using

@Rada8732 
A bit confused, are u saying the different version.
I just use the  `go get github.com/googlecodelabs/tools/claat` and `./claat export test.md`
As I am using ubuntu 20.04, I think I am using claat-linux-amd64 version? I meet the same [problem](https://github.com/googlecodelabs/tools/issues/539), cannot print the version
Just following the [sample](https://github.com/googlecodelabs/tools/blob/master/sample/codelab.md) for markdown syntax.

**Comment by Rada8732** [comment]
What open source you using

**Comment by rh-2019** [comment]
> What open source you using

@Rada8732 
Sry, I really do not understand. I just follow the sample code for installing the executable and download the sample markdown, then use the executable in cmd to generate/output the google codelab. what do open source and different tools mean?

**Comment by Rada8732** [comment]
Go to clatte

**Comment by zodiacVG** [comment]
I still meet the same question and am confused this question has remained for so long time...
