### ISSUE TITLE
getting SIGSEGV when exporting MD file

### ISSUE THREAD

**Issue by wescpy** [googlecodelabs/tools#570]
I'm getting a SIGSEGV when running the [latest/2.24](https://github.com/googlecodelabs/tools/releases/tag/v2.2.4) version of the [MacOS binary](https://github.com/googlecodelabs/tools/releases/download/v2.2.4/claat-darwin-amd64) on a Markdown file (output below). Running the [same request with the 2.2.2 binary](https://github.com/googlecodelabs/tools/releases/tag/v2.2.2) succeeds (also see output below).
```
$ ls -lsaFG ~/bin/claat*
23048 -rwxr-xr-x@ 1 wescpy  staff         11800192 May  5 19:06 /Users/wescpy/bin/claat*
18480 -rwxr-xr-x@ 1 wescpy  primarygroup   9463392 Sep 17  2020 /Users/wescpy/bin/claat222*
    0 lrwxr-xr-x  1 wescpy  primarygroup         5 May  5 19:13 /Users/wescpy/bin/claat224@ -> claat

$ which claat
/Users/wescpy/bin/claat

$ file ~/bin/claat*
/Users/wescpy/bin/claat:    Mach-O 64-bit executable x86_64
/Users/wescpy/bin/claat222: Mach-O 64-bit executable x86_64
/Users/wescpy/bin/claat224: Mach-O 64-bit executable x86_64

$ claat export google.md
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x132e359]

goroutine 54 [running]:
github.com/googlecodelabs/tools/claat/fetch/drive/auth.(*Helper).DriveClient(...)
        /Users/mco-gh/go/src/github.com/googlecodelabs/tools/claat/fetch/drive/auth/auth.go:90
github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).slurpRemoteBytes(0xc000250680, 0xc000344000, 0xac, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/mco-gh/go/src/github.com/googlecodelabs/tools/claat/fetch/fetch.go:396 +0x59
github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).slurpBytes(0xc000250680, 0x7ffeefbff5c5, 0xa, 0xc000320060, 0x1b, 0xc0003cd550, 0xac, 0x0, 0x0, 0x0, ...)
        /Users/mco-gh/go/src/github.com/googlecodelabs/tools/claat/fetch/fetch.go:258 +0x430
github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).SlurpImages.func1(0xc000250680, 0x7ffeefbff5c5, 0xa, 0xc000320060, 0x1b, 0xc000593140, 0xc00025cd20)
        /Users/mco-gh/go/src/github.com/googlecodelabs/tools/claat/fetch/fetch.go:209 +0x98
created by github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).SlurpImages
        /Users/mco-gh/go/src/github.com/googlecodelabs/tools/claat/fetch/fetch.go:207 +0x15a

$ claat222 export google.md
ok      drive-gcs-vision-sheets
```

**Comment by jgoerner** [comment]
Same here

**Comment by ux-8** [comment]
> I'm getting a SIGSEGV when running the [latest/2.24](https://github.com/googlecodelabs/tools/releases/tag/v2.2.4) version of the [MacOS binary](https://github.com/googlecodelabs/tools/releases/download/v2.2.4/claat-darwin-amd64) on a Markdown file (output below). Running the [same request with the 2.2.2 binary](https://github.com/googlecodelabs/tools/releases/tag/v2.2.2) succeeds (also see output below).
> 
> ```
> $ ls -lsaFG ~/bin/claat*
> 23048 -rwxr-xr-x@ 1 wescpy  staff         11800192 May  5 19:06 /Users/wescpy/bin/claat*
> 18480 -rwxr-xr-x@ 1 wescpy  primarygroup   9463392 Sep 17  2020 /Users/wescpy/bin/claat222*
>     0 lrwxr-xr-x  1 wescpy  primarygroup         5 May  5 19:13 /Users/wescpy/bin/claat224@ -> claat
> 
> $ which claat
> /Users/wescpy/bin/claat
> 
> $ file ~/bin/claat*
> /Users/wescpy/bin/claat:    Mach-O 64-bit executable x86_64
> /Users/wescpy/bin/claat222: Mach-O 64-bit executable x86_64
> /Users/wescpy/bin/claat224: Mach-O 64-bit executable x86_64
> 
> $ claat export google.md
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x132e359]
> 
> goroutine 54 [running]:
> github.com/googlecodelabs/tools/claat/fetch/drive/auth.(*Helper).DriveClient(...)
>         /Users/mco-gh/go/src/github.com/googlecodelabs/tools/claat/fetch/drive/auth/auth.go:90
> github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).slurpRemoteBytes(0xc000250680, 0xc000344000, 0xac, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0)
>         /Users/mco-gh/go/src/github.com/googlecodelabs/tools/claat/fetch/fetch.go:396 +0x59
> github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).slurpBytes(0xc000250680, 0x7ffeefbff5c5, 0xa, 0xc000320060, 0x1b, 0xc0003cd550, 0xac, 0x0, 0x0, 0x0, ...)
>         /Users/mco-gh/go/src/github.com/googlecodelabs/tools/claat/fetch/fetch.go:258 +0x430
> github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).SlurpImages.func1(0xc000250680, 0x7ffeefbff5c5, 0xa, 0xc000320060, 0x1b, 0xc000593140, 0xc00025cd20)
>         /Users/mco-gh/go/src/github.com/googlecodelabs/tools/claat/fetch/fetch.go:209 +0x98
> created by github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).SlurpImages
>         /Users/mco-gh/go/src/github.com/googlecodelabs/tools/claat/fetch/fetch.go:207 +0x15a
> 
> $ claat222 export google.md
> ok      drive-gcs-vision-sheets
> ```

**Comment by SURAPOL4** [comment]
> I'm getting a SIGSEGV when running the [latest/2.24](https://github.com/googlecodelabs/tools/releases/tag/v2.2.4) version of the [MacOS binary](https://github.com/googlecodelabs/tools/releases/download/v2.2.4/claat-darwin-amd64) on a Markdown file (output below). Running the [same request with the 2.2.2 binary](https://github.com/googlecodelabs/tools/releases/tag/v2.2.2) succeeds (also see output below).
> 
> ```
> $ ls -lsaFG ~/bin/claat*
> 23048 -rwxr-xr-x@ 1 wescpy  staff         11800192 May  5 19:06 /Users/wescpy/bin/claat*
> 18480 -rwxr-xr-x@ 1 wescpy  primarygroup   9463392 Sep 17  2020 /Users/wescpy/bin/claat222*
>     0 lrwxr-xr-x  1 wescpy  primarygroup         5 May  5 19:13 /Users/wescpy/bin/claat224@ -> claat
> 
> $ which claat
> /Users/wescpy/bin/claat
> 
> $ file ~/bin/claat*
> /Users/wescpy/bin/claat:    Mach-O 64-bit executable x86_64
> /Users/wescpy/bin/claat222: Mach-O 64-bit executable x86_64
> /Users/wescpy/bin/claat224: Mach-O 64-bit executable x86_64
> 
> $ claat export google.md
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x132e359]
> 
> goroutine 54 [running]:
> github.com/googlecodelabs/tools/claat/fetch/drive/auth.(*Helper).DriveClient(...)
>         /Users/mco-gh/go/src/github.com/googlecodelabs/tools/claat/fetch/drive/auth/auth.go:90
> github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).slurpRemoteBytes(0xc000250680, 0xc000344000, 0xac, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0)
>         /Users/mco-gh/go/src/github.com/googlecodelabs/tools/claat/fetch/fetch.go:396 +0x59
> github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).slurpBytes(0xc000250680, 0x7ffeefbff5c5, 0xa, 0xc000320060, 0x1b, 0xc0003cd550, 0xac, 0x0, 0x0, 0x0, ...)
>         /Users/mco-gh/go/src/github.com/googlecodelabs/tools/claat/fetch/fetch.go:258 +0x430
> github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).SlurpImages.func1(0xc000250680, 0x7ffeefbff5c5, 0xa, 0xc000320060, 0x1b, 0xc000593140, 0xc00025cd20)
>         /Users/mco-gh/go/src/github.com/googlecodelabs/tools/claat/fetch/fetch.go:209 +0x98
> created by github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).SlurpImages
>         /Users/mco-gh/go/src/github.com/googlecodelabs/tools/claat/fetch/fetch.go:207 +0x15a
> 
> $ claat222 export google.md
> ok      drive-gcs-vision-sheets
> ```
