### ISSUE TITLE
Bug: Cannot fetch remote images in markdown

### ISSUE THREAD

**Issue by dmattia** [googlecodelabs/tools#624]
The markdown code:

```md
![Creating a log monitor](https://avatars.githubusercontent.com/u/13681719?s=200&v=4)
```

Fails with error message:

```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1319795]

goroutine 20 [running]:
github.com/googlecodelabs/tools/claat/fetch/drive/auth.(*Helper).DriveClient(...)
        /Users/davidmattia/.go/pkg/mod/github.com/googlecodelabs/tools/claat@v0.0.0-20210818205155-ad98bab08ffe/fetch/drive/auth/auth.go:90
github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).slurpRemoteBytes(0xc00037c240, 0xc000181800, 0x3a, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/davidmattia/.go/pkg/mod/github.com/googlecodelabs/tools/claat@v0.0.0-20210818205155-ad98bab08ffe/fetch/fetch.go:412 +0x55
github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).slurpBytes(0xc00037c240, 0x7ffeefbff36d, 0x7, 0xc0001c5080, 0x12, 0xc0001b4880, 0x3a, 0x0, 0x0, 0x0, ...)
        /Users/davidmattia/.go/pkg/mod/github.com/googlecodelabs/tools/claat@v0.0.0-20210818205155-ad98bab08ffe/fetch/fetch.go:274 +0x408
github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).SlurpImages.func1(0xc00037c240, 0x7ffeefbff36d, 0x7, 0xc0001c5080, 0x12, 0xc00044f2c0, 0xc00049a070)
        /Users/davidmattia/.go/pkg/mod/github.com/googlecodelabs/tools/claat@v0.0.0-20210818205155-ad98bab08ffe/fetch/fetch.go:228 +0x98
created by github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).SlurpImages
        /Users/davidmattia/.go/pkg/mod/github.com/googlecodelabs/tools/claat@v0.0.0-20210818205155-ad98bab08ffe/fetch/fetch.go:226 +0x185
```

on the latest claat (but also on all versions I've used for around 2 years).

Of note, `<img>` tags are also not parsed for some reason

**Comment by modmscla** [comment]
same problem...

**Comment by AdnanAbbas1** [comment]
Same Problem!
