### ISSUE TITLE
New version of claat gives a panic: runtime error: slice bounds out of range [14891:14889]

### ISSUE THREAD

**Issue by beaumoaj** [googlecodelabs/tools#800]
Here is the output from running the new version of claat on one of my codelabs.

panic: runtime error: slice bounds out of range [14891:14889]

goroutine 18 [running]:
github.com/yuin/goldmark/text.(*Segment).Value(0xc000093730, {0xc00035e000, 0xc00027e700, 0x6fa7})
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/text/segment.go:48 +0x29d
github.com/yuin/goldmark/renderer/html.(*Renderer).writeLines(0xc0000ad8f0, {0x9d94d0, 0xc00027e700}, {0xc00035e000, 0x6fa7, 0x6fa7}, {0x9e0420, 0xc000227a40})
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/renderer/html/html.go:193 +0xbb
github.com/yuin/goldmark/renderer/html.(*Renderer).renderFencedCodeBlock(0xc0000ad8f0, {0x9d94d0, 0xc00027e700}, {0xc00035e000, 0x6fa7, 0x6fa7}, {0x9e0420, 0xc000227a40}, 0xd0)
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/renderer/html/html.go:285 +0x18b
github.com/yuin/goldmark/renderer.(*renderer).Render.func2({0x9e0420, 0xc000227a40}, 0xe0)
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/renderer/renderer.go:166 +0xc7
github.com/yuin/goldmark/ast.walkHelper({0x9e0420, 0xc000227a40}, 0xc0000939e0)
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/ast/ast.go:492 +0x34
github.com/yuin/goldmark/ast.walkHelper({0x9e0ae0, 0xc0002015f0}, 0xc0000939e0)
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/ast/ast.go:498 +0x8e
github.com/yuin/goldmark/ast.walkHelper({0x9e09c0, 0xc0002013b0}, 0xc0000939e0)
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/ast/ast.go:498 +0x8e
github.com/yuin/goldmark/ast.walkHelper({0x9e01e0, 0xc000200090}, 0xc0000939e0)
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/ast/ast.go:498 +0x8e
github.com/yuin/goldmark/ast.Walk(...)
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/ast/ast.go:487
github.com/yuin/goldmark/renderer.(*renderer).Render(0xc0000be9b0, {0x9ca960, 0xc00026e960}, {0xc00035e000, 0x6fa7, 0x6fa7}, {0x9e01e0, 0xc000200090})
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/renderer/renderer.go:161 +0x22d
github.com/yuin/goldmark.(*markdown).Convert(0xc00027e300, {0xc00035e000, 0x6fa7, 0x6fa7}, {0x9ca960, 0xc00026e960}, {0x0, 0x0, 0x0})
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/markdown.go:117 +0x10b
github.com/googlecodelabs/tools/claat/parser/md.renderToHTML({0xc000340000, 0xc0000b60f8, 0x30})
	/Users/marccohen/p/tools/claat/parser/md/parse.go:237 +0x1ff
github.com/googlecodelabs/tools/claat/parser/md.(*Parser).Parse(0x8929e0, {0x9cb3e0, 0xc0000b60f8}, {0x2})
	/Users/marccohen/p/tools/claat/parser/md/parse.go:120 +0x45
github.com/googlecodelabs/tools/claat/parser.Parse({0x8f60f3, 0x2}, {0x9cb3e0, 0xc0000b60f8}, {0xa720000000000000})
	/Users/marccohen/p/tools/claat/parser/parse.go:73 +0x73
github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).SlurpCodelab(0xc00027e280, {0x7ffcc362d453, 0xb}, {0x91fd78, 0x0})
	/Users/marccohen/p/tools/claat/fetch/fetch.go:154 +0x2a8
github.com/googlecodelabs/tools/claat/cmd.ExportCodelab({0x7ffcc362d453, 0x0}, {0x0, 0x0}, {{0x0, 0x0}, {0x8f6643, 0x3}, 0xc00026e750, {0x9003bc, ...}, ...})
	/Users/marccohen/p/tools/claat/cmd/export.go:105 +0x13c
github.com/googlecodelabs/tools/claat/cmd.CmdExport.func1({0x7ffcc362d453, 0xb})
	/Users/marccohen/p/tools/claat/cmd/export.go:73 +0x7c
created by github.com/googlecodelabs/tools/claat/cmd.CmdExport
	/Users/marccohen/p/tools/claat/cmd/export.go:72 +0x368

Here is the markdown

`author: Tony Beaumont
summary: Connecting to API
id: week04
categories: Android, Java
environments: Web
status: Published
feedback link: mailto:a.j.beaumont@aston.ac.uk

# Connecting to a JSON API

The application this week will connect to an API and download data in JSON format.  We will turn the data into a scrollable list view and provide a way to view the details of each item in the list in a different screen.

### What you should already know

* How to create and run an Android app
* How to navigate from one fragment to another
* How a `ViewModel` works.

### What you'll learn

* How to make a network request in a background thread
* How to process JSON data using Java classes to model the data
* How to display an image downloaded from the Internet
* How to use a `RecyclerView` to present a scrollable list of items
* How to display a Google Map with a marker on it.

### What you'll do

We will use a [Random User Generator](https://randomuser.me/) to download the details of a number of ficticious people, including images.  The data is downloaded in JSON format.  You can see some sample data for one random person by clicking [this link](https://randomuser.me/api).  Here is a sample of the kind of data we will be dealing with:
```
{
  "results": [
    {
      "gender": "male",
      "name": {
        "title": "Mr",
        "first": "Boris",
        "last": "Klimpush"
      },
      "location": {
        "street": {
          "number": 1794,
          "name": "Kupalska"
        },
        "city": "Tetiyiv",
        "state": "Ivano-Frankivska",
        "country": "Ukraine",
        "postcode": 64050,
        "coordinates": {
          "latitude": "76.0048",
          "longitude": "-136.6092"
        },
        "timezone": {
          "offset": "-7:00",
          "description": "Mountain Time (US & Canada)"
        }
      },
      "email": "boris.klimpush@example.com",
      "login": {
        "uuid": "16227d59-2c66-4143-94e4-7121fdd771c3",
        "username": "tinyfish514",
        "password": "deejay",
        "salt": "jUyAetnf",
        "md5": "79d5385452935194435ad4075559744a",
        "sha1": "6b56e0a923ff91d2e1f79d02ca32a7cdd4ed8216",
        "sha256": "ca2831dc76b6f490af432dcf1347416dc02a03984194197bdd97af25cb3f9855"
      },
      "dob": {
        "date": "1948-07-01T12:29:06.415Z",
        "age": 74
      },
      "registered": {
        "date": "2005-11-21T23:23:31.332Z",
        "age": 16
      },
      "phone": "(099) V84-4181",
      "cell": "(067) R72-8230",
      "id": {
        "name": "",
        "value": null
      },
      "picture": {
        "large": "https://randomuser.me/api/portraits/men/8.jpg",
        "medium": "https://randomuser.me/api/portraits/med/men/8.jpg",
        "thumbnail": "https://randomuser.me/api/portraits/thumb/men/8.jpg"
      },
      "nat": "UA"
    }
  ]
}
```

## The App we will build

We will be using [Retrofit](https://square.github.io/retrofit/) to download the data, we will also use [Picasso](https://square.github.io/picasso/) to fetch the image of the person from the URL provided in the data.

We will also use the location information provided to plot the person's location on a map.  As the data is random, many users are located in the middle of the ocean but we won't worry too much about that.

Here is a picture of the home screen of the app:

![Home Screen](HomeScreen.png "Home Screen")

This picture shows the details screen

![Details Screen](DetailsScreen.png "Details Screen")

## Create the App

Create a new Android project using the "Basic Activity" template.  This gives us a simple app with two screens, first fragment and second fragment.

## Create the data model

Before we do anything further, we need to look at the data.  If we make this call to the API, [https://randomuser.me/api?noinfo](https://randomuser.me/api?noinfo), (the `noinfo` property causes an "information" element to be omitted) the top level of the data looks like this:
```
{
  "results": [ ... ]
}
```
This represent an object with one field called `results`.  The type of the field is a list.  Each item in the list will be an object representing a `user`.  
```
{
  "results": [
    {
      "gender": "male",
      "name": {
        "title": "Mr",
        "first": "Boris",
        "last": "Klimpush"
      },
      // more fields omitted
    }
  ]
}
```

**Create a Java package** called `model` into which we will put the classes that will model our data.

### A `User` class

We need to create Java classes to represent each of these.  First we will create a class to represent a user:
```
public class User implements Serializable {
	// The "easy" fields.  These are all just text
	private String gender;
	private String email;
	private String phone;
	private String cell;
	private String nat;

}
```
The class implements `Serializable` because we eventually need to pass `User` objects as a parameter from the home screen to the details screen.

To extract data from a JSON file and turn it into Java classes, we need to create a field of the same name in the Java class to match that field in the JSON file.  The code above shows the easy fields which can be represented with a `String`.  Create the `User` class, enter the fields shown above and then use Android Studio to generate getter and setter methods for those fields.  To do that, **Right-click** the file, choose **Generate** then **getter and setter** and highlight all of the fields and click **OK**.

### A `Name` class

If you look at the data, the `name` field has a value that is itself an object.  In our sample data above it looks like this:
```
"name": {
    "title": "Mr",
    "first": "Boris",
    "last": "Klimpush"
},
```
Simple text or numeric fields can be assigned a text or numeric value, but object types must be assigned a matching object value.  The name of the field is `name` and so we should create a Java class called `Name` to hold the data that makes up a name.  Here is the class:
```
public class Name  implements Serializable {
	private String title;
	private String first;
	private String last;
    
}
```
Again the class is `Serializable` because it is part of a `User` class that is also `Serializable`.

Now **generate the getter and setter methods for this class** in the same way you did for the `User` class.

We need to add the `name` field to the `User` class now.  Add this field below the other fields in the `User` class:
```
private Name name;
```
and then **generate the getter and setter methods** for the `name` field.

### The `UserList` class

Create a class called `UserList`, it only has one field which is a list of user objects called `results`:
```
public class UserList {
	private ArrayList<User> results;
    
}
```
Again, **generate getter and setter methods** for this class.  We don't need to make this class `Serializable` because we actually only keep the list of users and throw away this wrapper when we get the data.  If you have model classes that need to be passed as parameters between fragments, you should make them `Serializable` (or `Parcelable`).

### Other classes

We will need to create classes to represent the `location` and the `picture` of the person.  We will be using the [Google Gson](https://github.com/google/gson) library to turn the JSON data into Java classes, and that library allows us to have partially complete data model classes.  If a field is missing, the JSON data for that field will be discarded.  We will defer the creation of `Location` and `Picture` classes until later.

### Utility methods

We have enough fields now to get some data from the API.  We will initially just print the names of each person in the data set.  To print a `User`, we should provide a `toString` method in the `User` class:
```
@Override
public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append(getName().getTitle());
    sb.append(" ");
    sb.append(getName().getFirst());
    sb.append(" ");
    sb.append(getName().getLast());
    return sb.toString();
}
```
Add this `toString` method to your `User` class.

## Create the `ViewModel`

The `ViewModel` class will keep track of the downloaded data and wrap it in `LiveData` wrapper so we can update the UI whenever our data changes.

1.  Create a class in your `model` package called `UsersViewModel`.
    ```
    public class UsersViewModel extends ViewModel {
        private MutableLiveData<List<User>> allUsers;

        public UsersViewModel() {
            super();
            allUsers = new MutableLiveData<>(new ArrayList<>());
        }

        public LiveData<List<User>> getAllUsers() {
            return allUsers;
        }	
    }
    ```
    As you can see, we have a list of users.

1.  Add a `UsersViewModel` field to `FirstFragment`:

    ```
    private UsersViewModel viewModel;
    ```
    and assign it a value inside `onCreateView`:
    ```
    viewModel = new ViewModelProvider(requireActivity()).get(UsersViewModel.class);
    ```

    
## Set up Retrofit and Gson

1.  The data to be stored in the view model will be downloaded using the Retrofit library.  We need to add Retrofit to the dependencies.  Choose **File** -> **Project Structure...**, select **Dependencies** and then **app**.  Click the **+** and choose **Library Dependency**.  Search for `com.squareup.retrofit2:retrofit` and select the entry with `Group ID` of `com.squareup.retrofit2`, and `Artifact Name` of `retrofit` and Repository `Maven Central`.  The version will be `2.9.0` (or newer).  Click **OK**, then **click Apply** but leave the **Project Structure** dialog open.
1.  Next, we need to add the Gson converter library to the dependencies because Retrofit will use the Gson library to convert the JSON data into Java objects.  In the **Project Structure** dialog, click the **+** again to add another **Library Dependency**.  Search for `com.squareup.retrofit2` and select the entry with `Group ID` of `com.squareup.retrofit2`, and `Artifact Name` of `converter-gson` and Repository `Maven Central`.  The version will be `2.0.0-beta2` (or newer).  **Click OK** and then **click Apply**.
1.  Click **OK** to close the **Project Structure** dialog.

### Define the API for Retrofit

1.  Create a new package called `service` and add a new `interface` called `RandomUser` to the `service` package.  This class defines the API calls that we will be using.  There could be several calls but we will only require one.
    ```
    import retrofit2.Call;
    import retrofit2.http.GET;
    import retrofit2.http.Query;
    import uk.ac.aston.api_example.model.UserList;

    public interface RandomUser {
        // For documentation see
        // https://randomuser.me/documentation

        @GET("api/?noinfo")
        Call<UserList> getUsers(@Query("results") Integer numUsers,
                                @Query("nat") String nat);
    }

    ```
    This code defines a `GET` request whose parameter is the path information and query string to be able to call the API.  We will add the base url of `https://randomuser.me/` elsewhere.  The `Call` is set to return a `UserList` object and also shows how we can provide additional parameters to the request at runtime.  This request will generate a URL something like `https://randomuser.me/api?noinfo&results=10&nat=gb` depending on what values we pass as the values of `results` and `nat`.  The `results` attribute defines how many users we will get back in the list and the `nat` attribute restricts the nationality of the returned users.  The full documentation for the API is [here](https://randomuser.me/documentation).

1.  Now we will create a **repository** that will provide a way of calling the API using the `RandomUser` interface we just defined.  You should put this into the `service` package as it goes with the `RandomUser` interface.  Here is the code for the repository class which is called `UserRepository`:
    ```
    public class UserRepository {
        private RandomUser randomUserService;

        public UserRepository(RandomUser userService) {
            this.randomUserService = userService;
        }

        public Call<UserList> getListOfUsers(int numUsers, String nationality) {
            return randomUserService.getUsers(numUsers, nationality);
        }
    }
    ```
    This class provide a method called `getListOfUsers` which requires our two parameters, the number of users to return and the nationality of those users.

1.  Set up the Retrofit object in our `FirstFragment`.  We will do this inside the `onViewCreated` method, because when we want to display the data in the UI, we know the view will have been created at this point.  Add this code to `FirstFragment.onViewCreated`:
    ```
    Retrofit retrofit = new Retrofit.Builder()
        .baseUrl("https://randomuser.me/")
        .addConverterFactory(GsonConverterFactory.create())
        .build();

    RandomUser service = retrofit.create(RandomUser.class);
    ```
    This is where we set the base URL for the API and we also specify that we use the Gson method for converting the response into Java classes.

1. Write a method in a `UsersViewModel` that will call the API and populate its list of users with the data we get back.
    ```
    public void requestRandomUsers(UserRepository userRepository) {
        if (allUsers.getValue().size() == 0) {
            Call<UserList> userCall = userRepository.getListOfUsers(25, "gb");
            userCall.enqueue(new Callback<UserList>() {
                @Override
                public void onResponse(Call<UserList> call, Response<UserList> response) {
                    if (response.isSuccessful()) {
                        Log.i("AJB", response.body().toString());
                        addAll(response.body());
                    }
                }

                @Override
                public void onFailure(Call<UserList> call, Throwable t) {
                    // show error message to user
                    Log.i("AJB", "Error: " + t.toString());
                }
            });
        } else {
            Log.i("AJB", "Already got a list of users, not getting any more");
        }
    }
    ```
    This method will only call the API once.  The outer `if` statement checks if we already have some data and does nothing if we already have data.  If we need to call the API it creates a `userCall` and puts it in the queue to be called, providing callbacks for success and failure.  If the call is successful, we will add the data to the list of allUsers.  The missing method is `addAll`:
    ```
    public void addAll(UserList list) {
		allUsers.getValue().addAll(list.getResults());
		allUsers.setValue(allUsers.getValue()); // to enable the callback
		Log.i("AJB", "Printing " + allUsers.getValue().size() + " Users");
		for (User user : allUsers.getValue()) {
			Log.i("AJB", user.toString());
		}
	}
    ```
    This method adds the entire list of users from the results to our `ArrayList`.  When we are observing `LiveData`, the callback is only invoked when the **value** changes and not when there are internal changes in a list.  Therefore we use the trick of assigning the list back to iteself to simulate the value changing.  Finally we print all the users out to the logcat.
    
1.  The app needs to access the Internet, so we need to add `user-permission` for that in the `AndroidManifest.xml`.  Add these two lines inside the `manifest` but BEFORE the `application` element:
    ```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    ```
    
1.  We are almost at the point where we can test the application.  Add the following line to the end of `FirstFragment.onViewCreated`
    ```
    viewModel.requestRandomUsers(new UserRepository(service));
    ```
    This will call the API and get a list of users back.

1.  Run the app, you should see the results printed in the logcat (nothing will appear in the UI yet).

## Make the UI respond to the new data

Now we are getting some data, we cam make the first steps in making the UI respond to the arrival of that data.  We will add this code into `FirstFragment`.  This code should go into `onViewCreated` because we can guarantee that the UI has been fully created at that time and we can access the widgets and make any modifications that we want to.

First we will create the `Observer` that will respond to the `LiveData` being updated.  Here is the code:
```
public void onViewCreated(@NonNull View view, Bundle savedInstanceState) {
    super.onViewCreated(view, savedInstanceState);
    // Create the observer which updates the UI.
    final Observer<List<User>> userListObserver = new Observer<List<User>>() {
        @Override
        public void onChanged(@Nullable final List<User> userList) {
            // Update the UI, in this case, a Toast.
            Toast.makeText(getContext(),
                "We got a list of " + userList.size() + " users", 
                Toast.LENGTH_LONG).show();
        }
    };
    // Other code omitted ... 
}
```
This code will pop up a `Toast` message indicating how many user details were received.

In order to use the `Observer` we need to add the following line of code.  This should be put after the assignment to `userListObserver`
```
viewModel.getAllUsers().observe(getViewLifecycleOwner(), userListObserver);
```

Run your app and this time you should see a `Toast` message when the data arrives.  Notice that you initially get a popup message saying we got 0 users. This occurs when the `Observer` first starts to observe the data, which is initially an empty list.  Eventually, when we get the data, you should see a message saying we got 20 users.

### Strategy for requesting data

Requesting data over the internet potentially costs the user money if they are paying for their data, so you need to be aware of that and only make essential requests.

You need to be aware of the `Fragment` lifecycle.  We can demonstrate that small changes to our code might have unintended effects.  In the `UsersViewModel.requestRandomUsers` method, comment out the `if` statement:
```
// if (allUsers.getValue().size() == 0) {
    Call<UserList> userCall = userRepository.getListOfUsers(25, "gb");
    //  Other code omitted...
// } else {
//    Log.i("AJB", "Already got a list of users, not getting any more");
//}
```

Run your app and notice that we get the initial 25 users.  Now navigate to the `SecondFragment` and then return to `FirstFragment`.  Notice we soon have 50 users because the network request was made again when the `FirstFragment` view was created.  You probably do not want to be repeating the network request every time that the the `FirstFragment` page loads.  Hence you need to have some logic build into your code to control the network requests that are made.

**Uncomment the IF statement** and return the code to how it was so we only get the one set of 25 users.

## Display the list of users

In this step we will use a `RecyclerView` to display the intire list of users on the screen.  First we need to set up the layout for `FirstFragment`.

Open `fragment_first.xml` and replace the existing code with the following:
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".FirstFragment">

    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/recyclerview"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

    </androidx.recyclerview.widget.RecyclerView>
</androidx.constraintlayout.widget.ConstraintLayout>
```

At this point I advise you to work through the codelab on Blackboard which takes you through the use of a `RecylerView`.  In this session we will somewhat rush through the steps required to create and use one.

1.  Our list will include small pictures of the users.  Therefore, we need to update our model so that we get the picture data.  In your `model` package, create a new class called `Picture` and give it the following fields:
    ```
    public class Picture  implements Serializable {
	    private String large;
	    private String medium;
	    private String thumbnail;
    }

    ```
    Then **generate getter and setter methods** for those fields.
    
1.  Update the `User` class to add the following field:
    ```
    private Picture picture;
    ```
    Then **generate getter and setter methods** for that field.
    
1.  Each row in our UI will contain some text (the name of the user) followed by an image of the user.  We need a layout for that.  Right-click your `res/layout` folder, and choose **New** -> **Layout Resource File**.  Name your new file `user_item` and set the **Root Element** to be `LinearLayout`.  open the layout file and edit it to contain the following layout:
    ```
    <?xml version="1.0" encoding="utf-8"?>
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
	    android:layout_width="match_parent"
	    android:layout_height="wrap_content"
	    android:orientation="horizontal"
	    android:weightSum="3"
	    android:padding="6dp">
	    <TextView
		    android:id="@+id/username"
		    android:layout_width="wrap_content"
		    android:layout_height="wrap_content"
		    android:layout_weight="2"
		    android:textSize="24sp"
		    android:textStyle="bold"/>
        <ImageView
		    android:id="@+id/userimage"
		    android:layout_weight="1"
		    android:layout_width="70dp"
		    android:layout_height="70dp"
		    android:scaleType="fitXY"/>
    </LinearLayout>
    ```
    Note that this creates a horizontal layout with the name first and the image second.  This layout will be used for each individual row in the list of users.
    
1.  We will use the **Picasso** library to load the image from the URL that is given to us when we load the user data.  Gor to **File** -> **Project Structure**.  Click **Dependencies** and then **app**.  Click the **+** and choose **Library Dependency** and search for `com.squareup.picasso:picasso`.  Select the result with `Group ID` of `com.squareup.picasso`, `Artifact Name` of `picasso` and `Repository` of `Maven Central`.  The version will be `2.71828` (or newer).  Click **OK**.

1.  We need an **adapter**.  The adapter provides the link between our `ArrayList<User>` and the list of items that appears on the screen using the layout we just created.  In your `model` package, create a new class called `UserListAdapter`:
    ```
    public class UserListAdapter extends
        RecyclerView.Adapter<UserListAdapter.UserViewHolder> {

	    private List<User> mUserList;
	    private final LayoutInflater mInflater;

	    public UserListAdapter(Context context,
						   List<User> userList) {
			mInflater = LayoutInflater.from(context);
		    this.mUserList = userList;
        }

	    @NonNull
	    @Override
	    public UserViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
		    View mItemView = mInflater.inflate(R.layout.user_item,
                parent, false);
		    return new UserViewHolder(mItemView, this);
        }

	    @Override
	    public void onBindViewHolder(@NonNull UserViewHolder holder, int position) {
		    User user = mUserList.get(position);
		    holder.user = user;
		    Name name = user.getName();
		    String thumb = user.getPicture().getMedium();
		    String displayName = name.getTitle() + " " + name.getFirst() + " " + name.getLast();
		    holder.usernameView.setText(displayName);
		    Picasso.get().load(thumb).into(holder.userImage);
        }

	    @Override
	    public int getItemCount() {
		    return this.mUserList.size();
        }

	    public void updateData(List<User> list) {
		    this.mUserList = list;
		    notifyDataSetChanged();
        }

	    class UserViewHolder extends RecyclerView.ViewHolder {
		    public final TextView usernameView;
		    public final ImageView userImage;
		    final UserListAdapter mAdapter;
		    public User user;

	        public UserViewHolder(@NonNull View itemView, UserListAdapter adapter) {
			    super(itemView);
			    usernameView = itemView.findViewById(R.id.username);
			    this.userImage = itemView.findViewById(R.id.userimage);
			    this.mAdapter = adapter;
		    }
        }
    }
    ```
    Note the inner class called `UserViewHolder` which access the widgets in our `user_item` layout.  Note also that the `UserListAdapter` keeps its own copy of the `List<User>`.
    
    We need to create the adapter and link it to the `RecyclerView` but we do not need to call any of its methods.  That will be done automatically while the view for the `FirstFragment` is being built.  The main part of the code in the `UserListAdapter` is to populate the `TextView` and the `ImageView` for each row in the list of users to be displayed.  Most of that happens in the method called `onBindViewHolder` which gets a `UserViewHolder` to be populated with data and a `position` indicating which user we are currently displaying.  This method includes a call to the `Picasso` library to load the image into the `ImageView`.  Finally note that the `updateData` method is used to update the list of users and then notify the adapter that the data has changed and the layout of the list should be rebuilt.
    
1.  In your `FirstFragment` class, **delete** the code relating to `buttonFirst`
    ```
    binding.buttonFirst.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View view) {
            NavHostFragment.findNavController(FirstFragment.this)
                .navigate(R.id.action_FirstFragment_to_SecondFragment);
        }
    });    
    ```
    We no longer have that button in the layout.
    
1.  In your `FirstFragment`, add a field for the `RecyclerView` and the `UserlistAdapter`:
    ```
    private RecyclerView mRecyclerView;
    private UserListAdapter mAdapter;
    ```
    
1.  In `FragmentFirst.onViewCreated`, add the following lines to link the adapter to the recycler view:
    ```
    // Get a handle to the RecyclerView.
    mRecyclerView = view.findViewById(R.id.recyclerview);
    // Create an adapter and supply the data to be displayed.
    mAdapter = new UserListAdapter(getContext(), viewModel.getAllUsers().getValue());
    // Connect the adapter with the RecyclerView.
    mRecyclerView.setAdapter(mAdapter);
    // Give the RecyclerView a default layout manager.
    mRecyclerView.setLayoutManager(new LinearLayoutManager(getContext()));
    ```
    This should go BEFORE the Retrofit code, so that the view is wired together before we try getting any data to display in it.

1.  The last step is to replace the `Toast` in your `Observer.onChanged` to pass the new data to the adapter:
    ```
    public void onChanged(@Nullable final List<User> userList) {
        // Update the UI
        mAdapter.updateData(userList);
	}
    ```
    
1.  Run your app.  You should see a list of users and their pictures.

## Summary

1.  We have accessed an API to download data in JSON format
1.  We create a Java model to hold the downloaded data
1.  We used a RecyclerView to display some of the data.

### Next Week

In the final app, we will add a "details" screen to display a marker on a Google Map using the data we have obtained here.  To use Google Maps, you need a Google account, have created a project on the Google Cloud Console and set up a Billing Account.  The Google Cloud Console is here: [https://cloud.google.com/](https://cloud.google.com/)

## More Help on creating your app

1. For some codelabs on creating the **user experience**, see [https://developer.android.com/courses/fundamentals-training/toc-v2#unit_2_user_experience](https://developer.android.com/courses/fundamentals-training/toc-v2#unit_2_user_experience)

1.  For some codelabs on **saving user data**, see: [https://developer.android.com/courses/fundamentals-training/toc-v2#unit_4_saving_user_data](https://developer.android.com/courses/fundamentals-training/toc-v2#unit_4_saving_user_data)

1.  Adding Geo Features (aka location functionality) to your app: [https://developer.android.com/courses/advanced-training/toc#unit_4_add_geo_features_to_your_apps](https://developer.android.com/courses/advanced-training/toc#unit_4_add_geo_features_to_your_apps)
`

**Comment by beaumoaj** [comment]
[Navigation.md](https://github.com/googlecodelabs/tools/files/9990970/Navigation.md)

If you remove the final code section (lines 414 to 417) from the attached markdown file, it formats fine.  With the very last section of code (414 to 417) included it generates  this error:

panic: runtime error: slice bounds out of range [18147:18145]

goroutine 6 [running]:
github.com/yuin/goldmark/text.(*Segment).Value(0xc000061730, {0xc000378000, 0xc0002a4740, 0x46e9})
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/text/segment.go:48 +0x29d
github.com/yuin/goldmark/renderer/html.(*Renderer).writeLines(0xc00000d908, {0x9d94d0, 0xc0002a4740}, {0xc000378000, 0x46e9, 0x46e9}, {0x9e0420, 0xc000267c20})
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/renderer/html/html.go:193 +0xbb
github.com/yuin/goldmark/renderer/html.(*Renderer).renderFencedCodeBlock(0xc00000d908, {0x9d94d0, 0xc0002a4740}, {0xc000378000, 0x46e9, 0x46e9}, {0x9e0420, 0xc000267c20}, 0xd0)
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/renderer/html/html.go:285 +0x18b
github.com/yuin/goldmark/renderer.(*renderer).Render.func2({0x9e0420, 0xc000267c20}, 0xe0)
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/renderer/renderer.go:166 +0xc7
github.com/yuin/goldmark/ast.walkHelper({0x9e0420, 0xc000267c20}, 0xc0000619e0)
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/ast/ast.go:492 +0x34
github.com/yuin/goldmark/ast.walkHelper({0x9e0ae0, 0xc0002a7c20}, 0xc0000619e0)
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/ast/ast.go:498 +0x8e
github.com/yuin/goldmark/ast.walkHelper({0x9e09c0, 0xc0002a7a70}, 0xc0000619e0)
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/ast/ast.go:498 +0x8e
github.com/yuin/goldmark/ast.walkHelper({0x9e01e0, 0xc0002a6090}, 0xc0000619e0)
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/ast/ast.go:498 +0x8e
github.com/yuin/goldmark/ast.Walk(...)
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/ast/ast.go:487
github.com/yuin/goldmark/renderer.(*renderer).Render(0xc00007ca00, {0x9ca960, 0xc000296990}, {0xc000378000, 0x46e9, 0x46e9}, {0x9e01e0, 0xc0002a6090})
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/renderer/renderer.go:161 +0x22d
github.com/yuin/goldmark.(*markdown).Convert(0xc0002a4340, {0xc000378000, 0x46e9, 0x46e9}, {0x9ca960, 0xc000296990}, {0x0, 0x0, 0x0})
	/Users/marccohen/go/pkg/mod/github.com/yuin/goldmark@v1.3.7/markdown.go:117 +0x10b
github.com/googlecodelabs/tools/claat/parser/md.renderToHTML({0xc0002d2000, 0xc00000e108, 0x30})
	/Users/marccohen/p/tools/claat/parser/md/parse.go:237 +0x1ff
github.com/googlecodelabs/tools/claat/parser/md.(*Parser).Parse(0x8929e0, {0x9cb3e0, 0xc00000e108}, {0x2})
	/Users/marccohen/p/tools/claat/parser/md/parse.go:120 +0x45
github.com/googlecodelabs/tools/claat/parser.Parse({0x8f60f3, 0x2}, {0x9cb3e0, 0xc00000e108}, {0xa720000000000000})
	/Users/marccohen/p/tools/claat/parser/parse.go:73 +0x73
github.com/googlecodelabs/tools/claat/fetch.(*Fetcher).SlurpCodelab(0xc0002a42c0, {0x7ffd376703e4, 0xd}, {0x91fd78, 0x0})
	/Users/marccohen/p/tools/claat/fetch/fetch.go:154 +0x2a8
github.com/googlecodelabs/tools/claat/cmd.ExportCodelab({0x7ffd376703e4, 0x0}, {0x0, 0x0}, {{0x0, 0x0}, {0x8f6643, 0x3}, 0xc000296780, {0x9003bc, ...}, ...})
	/Users/marccohen/p/tools/claat/cmd/export.go:105 +0x13c
github.com/googlecodelabs/tools/claat/cmd.CmdExport.func1({0x7ffd376703e4, 0xd})
	/Users/marccohen/p/tools/claat/cmd/export.go:73 +0x7c
created by github.com/googlecodelabs/tools/claat/cmd.CmdExport
	/Users/marccohen/p/tools/claat/cmd/export.go:72 +0x368
